{
 "title": "Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "info",
     "query": "SELECT last(\"online\") AS \"Status\" , last(\"adress\") AS \"Address\" FROM \"info\"  GROUP BY \"worker\" ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "adress" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "master",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node1" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node2" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node3" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "master",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node1" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node2" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node3" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "master",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node1" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node2" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "worker", "operator": "=", "value": "node3" }
     ]
    }
   ]
  }
 ]
}